### ISSUE TITLE
fctx_set_rotation wont working on text

### ISSUE THREAD

**Issue by markgravity** [jrmobley/pebble-fctx#10]
Hi, i was tested on your test-app, changed the angle at
line 122
`fctx_set_rotation(&fctx, 90);`

but the text is not rotated.
I also testing on the other: https://github.com/jrmobley/pebble-laughing-demo. It's was same :(
I really like your project, hope you can fix it soon.

**Comment by jrmobley** [comment]
You probably already figured out that you needed to convert the angle to Pebble's units:
`fctx_set_rotation(&fctx, 90 * TRIG_MAX_ANGLE / 360)`
