### ISSUE TITLE
Version for diorite

### ISSUE THREAD

**Issue by gregoiresage** [jrmobley/pebble-fctx#11]
Could you please publish a package compatible with diorite ? :)

Thanks !

**Comment by gregoiresage** [comment]
mmmm looks like we can explicitely install the 1.3.0 but if we don't specify the version the 1.2.0 is found

**Comment by jrmobley** [comment]
Published v1.4.0.  No code changes, just rebuilt with the released SDK 4.0 and including diorite support.
