### ISSUE TITLE
`pivot` transformation is not mentioned in the readme

### ISSUE THREAD

**Issue by Krastanov** [jrmobley/pebble-fctx#12]
There might be some other docs that I missed, but for the moment I assume the only docs are the readme.

The pivot transform is not mentioned in the readme. I got it to work for me with a bit of experimenting, but it would be great to have it explained together with the other transforms.

I would make a PR with the explanation myself, but I do not understand it well, especially in terms of ordering with respect to the other transforms.

Thanks for writing this library!

**Comment by jrmobley** [comment]
Good catch and good timing!  I was just preparing v1.6.  I hope my terse notes on the pivot point are helpful.  And you are correct that the README and the header are the only docs.
