### ISSUE TITLE
Function to get the width of a string in pixels when drawn at a given size

### ISSUE THREAD

**Issue by stefanheule** [jrmobley/pebble-fctx#13]
It would be nice to have a function to get the width of a given string in pixels when it is drawn at a particular width, similar to graphics_text_layout_get_content_size from the Pebble SDK.  Alternatively, fctx_draw_string could return that value.

Would you consider adding this functionality (or is it already there and I missed it)?

**Comment by jrmobley** [comment]
Hmm... you are right, that should be exposed as a function.

**Comment by stefanheule** [comment]
Looking at the source code, this should actually be very simple to do.  I'd be happy to take a stab and give you a pull request, if you want.  Does having a function `fixed_t fctx_string_width(const char* text, FFont* font)` sound good to you?  Or would you prefer some other kind of API?

**Comment by jrmobley** [comment]
You are going to need to pass in the FContext\* as well, so that you can scale the width appropriately.  But otherwise, that is a good function signature I'd say.

**Comment by jrmobley** [comment]
And... there is totally a bug in the string width calculation in `fctx_draw_string`.

**Comment by stefanheule** [comment]
In that case I'll leave this ticket to you, because I was going to use the code in `fctx_draw_string` (which doesn't use a FContext).

**Comment by jrmobley** [comment]
Fixed in commit 589a1a1a04d520579b1261ceb8f73ef136dcf21f (v1.6.2).

**Comment by stefanheule** [comment]
Great, thank you a lot!  Great library :-)
