### ISSUE TITLE
fctx_draw_string isn't UTF-8 aware

### ISSUE THREAD

**Issue by unwiredben** [jrmobley/pebble-fctx#5]
The code at https://github.com/jrmobley/pebble-fctx/blob/master/fctx.c#L918 treats each character of the text string as its own glyph.  This won't work for UTF-8 encoded strings where characters above 127 are represented as multiple bytes.  Since Pebble's graphics_draw_text is explicitly marked as taking UTF-8, this should either be fixed or documented to not surprise programmers using the library.

**Comment by alinanorakari** [comment]
I have this problem, which can be observed when passing fctx_draw_string a string containing "°" or "\u00B0" respectively. Expected output: "°". Actual output: "Â°"

**Comment by jrmobley** [comment]
Okay!  UTF-8 decoding has been added as of commit 9cd558f642c55e005c3010583a5487c0bb48e14b.
Be sure to also update to https://github.com/jrmobley/pebble-fctx-compiler/commit/b7bf22ca3d3ba516ca5c724d3342e92b25f3e826 and rebuild your fonts.  The font data format has changed to support sparse glyph tables.  This should save some space if you are using those higher code points.
