### ISSUE TITLE
letter-spacing increased

### ISSUE THREAD

**Issue by alinanorakari** [jrmobley/pebble-fctx#6]
Letter-spacing has increased in the latest commit 9cd558f. Using the same svg font files, the newly generated ffont files used in the latest fctx produce significantly wider lines than ffont files from the same svg sources compiled for and used with the previous fctx release. There were no code changes in the watchface. I could observe this on centered and right justified lines, but have no left justified lines to confirm it also happens there.
Example screenshot before and after
![fctx-letter-spacing](https://cloud.githubusercontent.com/assets/4239297/12866178/e02ada9c-ccc4-11e5-89e2-42035b9835c2.jpg)

**Comment by alinanorakari** [comment]
on closer inspection it seems the problem might be in the compiler, not fctx itself

**Comment by alinanorakari** [comment]
I tried finding the origin of the problem but only got as far as that if I take metadata.emScale*0.9 in the compiler it produces something fairly close to the expected result. Hope that helps

**Comment by jrmobley** [comment]
Good catch!  The problem was in the compiler.  Fixed by https://github.com/jrmobley/pebble-fctx-compiler/commit/cf966743acd2ce87998c2bfdbb462ef5db588e08.

**Comment by alinanorakari** [comment]
thank you for the excellent work and fast fixing
