### ISSUE TITLE
Drawing text won't work in Aplite

### ISSUE THREAD

**Issue by hitormiss** [jrmobley/pebble-fctx#9]
Is there some trick to getting text drawing to work in Aplite?

Drawing text in Basalt & Chalk seems to work fine, but every time I try to run the same code in Aplite, I get the following error message:

`[ERROR] fctx.c:39: NULL fctx->flag_buffer`

Any ideas?

**Comment by jrmobley** [comment]
I would have to guess that you are out of memory.  Aplite doesn't have very much and a font with a complete character set is pretty large...

**Comment by hitormiss** [comment]
Aha. It appears that was the case -- I swapped in a much smaller compiled Font and now it's working.  thanks!
